# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import telemetria_pb2 as telemetria__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in telemetria_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OraculoServiceStub(object):
    """Servico de Sintonizacao de Fase entre Linguagem e Materia
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InterseccaoGeometrica = channel.unary_unary(
                '/telemetria.OraculoService/InterseccaoGeometrica',
                request_serializer=telemetria__pb2.TensorSeno.SerializeToString,
                response_deserializer=telemetria__pb2.TensorCosseno.FromString,
                _registered_method=True)


class OraculoServiceServicer(object):
    """Servico de Sintonizacao de Fase entre Linguagem e Materia
    """

    def InterseccaoGeometrica(self, request, context):
        """RPC: Recebe o Tensor da Linguagem (Seno) e devolve o Tensor da Materia (Cosseno)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OraculoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InterseccaoGeometrica': grpc.unary_unary_rpc_method_handler(
                    servicer.InterseccaoGeometrica,
                    request_deserializer=telemetria__pb2.TensorSeno.FromString,
                    response_serializer=telemetria__pb2.TensorCosseno.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'telemetria.OraculoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('telemetria.OraculoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OraculoService(object):
    """Servico de Sintonizacao de Fase entre Linguagem e Materia
    """

    @staticmethod
    def InterseccaoGeometrica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telemetria.OraculoService/InterseccaoGeometrica',
            telemetria__pb2.TensorSeno.SerializeToString,
            telemetria__pb2.TensorCosseno.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
