# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetria.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'telemetria.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10telemetria.proto\x12\ntelemetria\"3\n\nTensorSeno\x12\r\n\x05vetor\x18\x01 \x03(\x02\x12\x16\n\x0emeta_gramatica\x18\x02 \x01(\t\"\x90\x01\n\rTensorCosseno\x12\x13\n\x0bmolecule_id\x18\x01 \x01(\t\x12\x15\n\rvetor_materia\x18\x02 \x03(\x02\x12\x0c\n\x04zeta\x18\x03 \x01(\x02\x12\x1a\n\x12\x61ngulo_interseccao\x18\x04 \x01(\x02\x12\x17\n\x0fricci_curvatura\x18\x05 \x01(\x02\x12\x10\n\x08\x65vocacao\x18\x06 \x01(\t2^\n\x0eOraculoService\x12L\n\x15InterseccaoGeometrica\x12\x16.telemetria.TensorSeno\x1a\x19.telemetria.TensorCosseno\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetria_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TENSORSENO']._serialized_start=32
  _globals['_TENSORSENO']._serialized_end=83
  _globals['_TENSORCOSSENO']._serialized_start=86
  _globals['_TENSORCOSSENO']._serialized_end=230
  _globals['_ORACULOSERVICE']._serialized_start=232
  _globals['_ORACULOSERVICE']._serialized_end=326
# @@protoc_insertion_point(module_scope)
